name: Test Workflow

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@master
      - id: setup_nodejs
        name: Setup node.js
        uses: actions/setup-node@master
        with:
          node-version: 12
      - id: npm_ci
        name: npm ci
        run: npm ci
      - id: npm_test
        name: Test
        run: npm test
      - id: npm_run_build
        name: Build
        run: npm run build
